# Generated by Django 3.1 on 2020-10-06 12:12

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=100)),
                ('title', models.CharField(max_length=2000)),
                ('short_text', models.TextField()),
                ('body_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date', models.DateTimeField(max_length=12)),
                ('time', models.TimeField(default='00:00', max_length=12)),
                ('image', models.ImageField(upload_to='blog/image')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=100)),
                ('category_name_in_samll', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('feedback', models.TextField()),
                ('image', models.ImageField(default='', upload_to='testimonial/image')),
            ],
            options={
                'verbose_name_plural': 'Testimonial',
            },
        ),
        migrations.CreateModel(
            name='My_Work_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='My_Work_Category/image')),
                ('category_name_in_small', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Main_App.category')),
            ],
            options={
                'verbose_name_plural': 'My_Work_Categories',
            },
        ),
    ]
