# Generated by Django 3.1 on 2020-10-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name_in_samll',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='Category/image'),
        ),
        migrations.DeleteModel(
            name='My_Work_Category',
        ),
    ]
