# Generated by Django 3.1 on 2020-11-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0004_auto_20201006_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo1', models.ImageField(default='', upload_to='logo1/image')),
                ('logo2', models.ImageField(default='', upload_to='logo2/image')),
            ],
            options={
                'verbose_name_plural': 'Logo',
            },
        ),
    ]
