# Generated by Django 3.1 on 2020-11-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0006_auto_20201109_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(default='', upload_to='header/image')),
            ],
            options={
                'verbose_name_plural': 'Header Image',
            },
        ),
    ]
