# Generated by Django 3.1 on 2020-11-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0007_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(default='', upload_to='about/image')),
            ],
            options={
                'verbose_name_plural': 'AboutUs Image',
            },
        ),
    ]
