# Generated by Django 3.1 on 2020-11-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0008_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='about_info',
            field=models.TextField(default=''),
        ),
    ]
