# Generated by Django 3.1 on 2020-11-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0009_aboutus_about_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hireme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hireme_image', models.ImageField(default='', upload_to='Hireme/image')),
            ],
            options={
                'verbose_name_plural': 'Hireme Image',
            },
        ),
    ]
