# Generated by Django 3.1 on 2020-11-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0012_contactimage_testimonialimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us '},
        ),
    ]
